### ISSUE TITLE
Allow to remove default embeds from links in messages

### ISSUE THREAD

**Issue by juraj-hrivnak** [hugoalh/send-discord-webhook-ghaction#400]
### Describe

By default links to GitHub and other sites have their own embeds, which can clutter the channel a lot.

### Expected Behaviour

Be able to remove default embeds from messages.

**Comment by juraj-hrivnak** [comment]
There is a way to remove embeds from link by wrapping it in `<>`.

**Comment by hugoalh** [comment]
Added in commit ef7365d61fe1f301b1dc4c4e58e873764b353518.
